<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ItemTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('items')->delete();
        DB::table('items')->insert(array(
            0 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            1 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            2 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            3 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            4 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            5 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            6 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            7 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            8 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            9 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            10 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            11 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
            12 =>
            array(
                'name' => fake()->unique()->name(),
                'code' => "65012".fake()->unique()->numberBetween($min = 100, $max = 999),
                'active' => 1,
                'remarks' => fake()->text($maxNbChars = 200),
                'item_img' => 'img_'.fake()->unixTime($max = 'now'),
                'purchase_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'selling_price' => fake()->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 10000),
                'stock_minimum' => fake()->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 100),
                'stock_available' => fake()->randomFloat($nbMaxDecimals = 2, $min = 100, $max = 1000),
                'fsn' => 'fast-moving',
                'unit_id' => fake()->numberBetween($min = 1, $max = 7),
                'category_id' => fake()->numberBetween($min = 1, $max = 10),
                'created_by' => fake()->numberBetween($min = 1, $max = 20),
                'updated_by' => fake()->numberBetween($min = 1, $max = 20),
            ),
        ));
    }
}
